no_balance_label = "GBP: No Update"
reset_label = "GBP: Reset"

[points]
"Atomic" = 2
"Balance/Rebalance" = -8
"Code Improvement" = 2
"Mechanic" = -10
"Feedback" = 2
"Fix" = 3
"Grammar and Formatting" = 1
"Hard Deletes" = 12
"Logging" = 1
"Performance" = 12
"Priority: CRITICAL" = 20
"Priority: High" = 15
"Quality of Life" = 1
"Content Expansion" = -3
"Refactor" = 10
"Sound" = 3
"Sprites" = 3
"Unit Tests" = 6
