no_balance_label = "GBP: No Update"
reset_label = "GBP: Reset"

[points]
"Atomic" = 2
"Balance/Rebalance" = -8
"Code Improvement" = 2
"Feature" = -10
"Feedback" = 2
"Fix" = 3
"Grammar and Formatting" = 1
"Logging" = 1
"Performance" = 12
"Priority: CRITICAL" = 20
"Priority: High" = 15
"Quality of Life" = 1
"Refactor" = 10
"Sound" = 1
"Sprites" = 1
"Unit Tests" = 6
