#pretending we're C because otherwise ruby/rvm will initialize, even with "language: dm".
language: c

env:
  BYOND_MAJOR="503"
  BYOND_MINOR="1224"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install libc6:i386 libgcc1:i386 libstdc++6:i386 -qq

install:
  - curl "http://www.byond.com/download/build/${BYOND_MAJOR}/${BYOND_MAJOR}.${BYOND_MINOR}_byond_linux.zip" -o byond.zip
  - unzip byond.zip
  - cd byond
  - sudo make install
  - cd ..

script:
  - DreamMaker tgstation.dme
