#pretending we're C because otherwise ruby/rvm will initialize, even with "language: dm".
language: c

env:
    global:
    - BYOND_MAJOR="506"
    - BYOND_MINOR="1247"
    matrix:
    - DM_MAPFILE="tgstation2"
    - DM_MAPFILE="metastation"
    - DM_MAPFILE="ministation"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install libc6:i386 libgcc1:i386 libstdc++6:i386 -qq
  - sudo apt-get install python -qq
  - sudo apt-get install python-pip -qq
  - sudo pip install PyYaml -q
  - sudo pip install beautifulsoup4 -q

install:
  - curl "http://www.byond.com/download/build/${BYOND_MAJOR}/${BYOND_MAJOR}.${BYOND_MINOR}_byond_linux.zip" -o byond.zip
  - unzip byond.zip
  - cd byond
  - sudo make install
  - cd ..

script:
  - bash dm.sh -M${DM_MAPFILE} tgstation.dme
  - python tools/ss13_genchangelog.py html/changelog.html html/changelogs
