#pretending we're C because otherwise ruby will initialize, even with "language: dm".
language: c
sudo: false

env:
    global:
    - BYOND_MAJOR="508"
    - BYOND_MINOR="1293"
    matrix:
    - DM_MAPFILE="tgstation2"
    - DM_MAPFILE="metastation"
    - DM_MAPFILE="ministation"
  
cache:
  directories:
    - $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}
  
addons:
  apt:
    packages:
      - libc6-i386
      - libgcc1:i386
      - libstdc++6:i386
      - python
      - python-pip
  
install:
  - pip install --user PyYaml -q
  - pip install --user beautifulsoup4 -q

before_script:
  - chmod +x ./install-byond.sh
  - ./install-byond.sh

script:
  - shopt -s globstar
  - (! grep 'step_[xy]' maps/**/*.dmm)
  - (! find nano/templates/ -type f -exec md5sum {} + | sort | uniq -D -w 32 | grep nano)
  - md5sum -c - <<< "88490b460c26947f5ec1ab1bb9fa9f17 *html/changelogs/example.yml"
  - python tools/GenerateChangelog/ss13_genchangelog.py html/changelog.html html/changelogs
  - source $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}/byond/bin/byondsetup
  - bash dm.sh -M${DM_MAPFILE} tgstation.dme
