contact_links:
  - name: Feature Requests
    url: https://tgstation13.org/phpBB/viewforum.php?f=9
    about: Post feature requests and suggestions on the forums. This repository does not handle them.
