name: Autobuild TGUI

on:
  push:
    branches:
      - 'master'
    paths:
      - 'tgui/**.js'
      - 'tgui/**.scss'

jobs:
  build:
    name: Rebuild TGUI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 25
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '>=12.13'
      - name: Build TGUI
        run: bin/tgui --ci
        working-directory: ./tgui
      - name: Commit Artifacts
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "TGUI"
          git pull origin master
          git commit -m "Automatic TGUI Rebuild [ci skip]" -a || true
      - name: Push Artifacts
        uses: ad-m/github-push-action@master
        env:
          GITHUB_ACTOR: comfyorange
        with:
          github_token: ${{ secrets.GITHUB_MASTER_KEY }}
