name: Autowiki
on:
  schedule:
    - cron: "5 4 * * *"
  workflow_dispatch:
permissions:
  contents: read

jobs:
  autowiki:
    runs-on: ubuntu-latest
    steps:
      - name: "Check for AUTOWIKI_USERNAME"
        id: secrets_set
        env:
          ENABLER_SECRET: ${{ secrets.AUTOWIKI_USERNAME }}
        run: |
          unset SECRET_EXISTS
          if [ -n "$ENABLER_SECRET" ]; then SECRET_EXISTS=true ; fi
          echo "SECRETS_ENABLED=$SECRET_EXISTS" >> $GITHUB_OUTPUT
      - name: Checkout
        if: steps.secrets_set.outputs.SECRETS_ENABLED
        uses: actions/checkout@v4
      - name: Install BYOND
        if: steps.secrets_set.outputs.SECRETS_ENABLED
        uses: ./.github/actions/restore_or_install_byond
      - name: Install rust-g
        if: steps.secrets_set.outputs.SECRETS_ENABLED
        run: |
          bash tools/ci/install_rust_g.sh
      - name: Compile and generate Autowiki files
        if: steps.secrets_set.outputs.SECRETS_ENABLED
        run: |
          source $HOME/BYOND/byond/bin/byondsetup
          tools/build/build.sh --ci autowiki
      - name: Run Autowiki
        if: steps.secrets_set.outputs.SECRETS_ENABLED
        env:
          USERNAME: ${{ secrets.AUTOWIKI_USERNAME }}
          PASSWORD: ${{ secrets.AUTOWIKI_PASSWORD }}
        run: |
          cd tools/autowiki
          npm install
          cd ../..
          node tools/autowiki/autowiki.js data/autowiki_edits.txt data/autowiki_files/
