name: Compile changelogs

on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  compile:
    name: "Compile changelogs"
    runs-on: ubuntu-latest
    steps:
      - name: "Setup python"
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: "Install deps"
        run: |
          python -m pip install --upgrade pip
          python -m pip install pyyaml
      - name: "Checkout"
        uses: actions/checkout@v1
        with:
          fetch-depth: 25
      - name: "Compile"
        run: |
          python tools/ss13_genchangelog.py html/changelog.html html/changelogs
      - name: Commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Changelogs"
          git pull origin master
          git commit -m "Automatic changelog compile [ci skip]" -a || true
      - name: "Push"
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_MASTER_KEY }}
