name: Docker Build
on:
  schedule:
  - cron: "19 1 * * *"
  workflow_dispatch:
jobs:
  publish:
    if: ( !contains(github.event.head_commit.message, '[ci skip]') )
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - name: Build and Publish Docker Image to Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: tgstation/tgstation
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: Dockerfile
          tags: "latest"
