name: Generate documentation
on:
  schedule:
  - cron: "44 */6 * * *"
  workflow_dispatch:
permissions:
  contents: read
jobs:
  generate_documentation:
    permissions:
      contents: write  # for JamesIves/github-pages-deploy-action to push changes in repo
    if: ( !contains(github.event.head_commit.message, '[ci skip]') )
    runs-on: ubuntu-22.04
    concurrency: gen-docs
    steps:
      - uses: actions/checkout@v4
      - name: Setup cache
        uses: actions/cache@v4
        with:
          path: ~/SpacemanDMM
          key: ${{ runner.os }}-spacemandmm-${{ secrets.CACHE_PURGE_KEY }}
      - name: Install SpacemanDMM
        run: bash tools/ci/install_spaceman_dmm.sh dmdoc
      - name: Generate documentation
        run: |
          ~/dmdoc
          touch dmdoc/.nojekyll
          echo codedocs.tgstation13.org > dmdoc/CNAME
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          BRANCH: gh-pages
          CLEAN: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SINGLE_COMMIT: true
          FOLDER: dmdoc
