name: Update TGS DMAPI

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-dmapi:
    runs-on: ubuntu-22.04
    name: Update the TGS DMAPI
    permissions:
      contents: write
      pull-requests: write
    steps:
    - name: Clone
      uses: actions/checkout@v4

    - name: Branch
      run: |
        git branch -f tgs-dmapi-update
        git checkout tgs-dmapi-update
        git reset --hard master

    - name: Apply DMAPI update
      uses: tgstation/tgs-dmapi-updater@v2
      id: dmapi-update
      with:
        header-path: 'code/__DEFINES/tgs.dm'
        library-path: 'code/modules/tgs'

    - name: Commit and Push
      continue-on-error: true
      run: |
        git config user.name "tgstation-ci[bot]"
        git config user.email "179393467+tgstation-ci[bot]@users.noreply.github.com"
        git add .
        git commit -m 'Update TGS DMAPI'
        git push -f -u origin tgs-dmapi-update

    - name: Generate App Token
      id: app-token-generation
      uses: actions/create-github-app-token@v1
      if: env.APP_PRIVATE_KEY != '' && env.APP_ID != ''
      with:
        app-id: ${{ secrets.APP_ID }}
        private-key: ${{ secrets.APP_PRIVATE_KEY }}
      env:
        APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
        APP_ID: ${{ secrets.APP_ID }}

    - name: Create Pull Request
      uses: repo-sync/pull-request@v2
      if: ${{ success() }}
      with:
        source_branch: "tgs-dmapi-update"
        destination_branch: "master"
        pr_title: "Automatic TGS DMAPI Update"
        pr_body: "This pull request updates the TGS DMAPI to the latest version. Please note any changes that may be breaking or unimplemented in your codebase by checking what changes are in the definitions file: code/__DEFINES/tgs.dm before merging.\n\n${{ steps.dmapi-update.outputs.release-notes }}"
        pr_label: "Tools"
        pr_allow_empty: false
        github_token: ${{ steps.app-token-generation.outputs.token || secrets.GITHUB_TOKEN }}
